# Các cài đặt liên quan đến Discord
discord:
  # Các Token của bot
  token:
    client_1: # Của bot thứ nhất (bắt buộc)
    client_2: # Của bot thứ hai (không cần thiết)
  # Các ID của kênh
  channel:
    command_log: # ID của kênh nhận các thông báo khi có lệnh được thực thi
    error_log: # ID của kênh nhận các thông báo lỗi
  # Các chỉnh sửa liên quan đến các câu lệnh
  commands:
    exclude: [
        "eval",
        "log",
        # ...
      ] # Các câu lệnh sẽ không xuất hiện
  owner:
    id: # ID của onwer của bot

# Các cài đặt liên quan đến Minecraft
minecraft:
  # Tài khoản của bot
  account:
    username: player # Có thể là tên hoặc mail đã đăng ký Minecraft bản quyền
    password: # Là mật khẩu của mail ở trên, bỏ trống nếu là tài khoản crack
  # Các cài đặt liên quan đến tài khoản trong server
  # Bỏ qua nếu server đều không hỗ trợ hay phương thức đăng nhập này
  ingame:
    pin: 0 0 0 0 # Pin của bot
    pass: igpass # Pass trong server của bot (đang nhập theo kiểu '/login <pass>')
  # Các cài đặt liên quan đến Server
  server:
    ip: hypixel.com # IP của máy chủ
    server: 1.16.5 # Version của máy chủ (hiện tại chỉ hỗ trợ phiên bản từ 1.8 - 1.19)
    port: 25565 # Cổng của máy chủ (mặc định là 25565)
    reconnectTimeout: 2m # Thời gian để bot kết nối lại với server khi bị kick (viết theo định dạng h, m, s; vd: 5m)
    chatTimeout: 2m # Thời gian giữa các tin nhắn (viết theo định dạng h, m, s; vd: 5m)
    login:
      # Cách login vào server
      # Có 3 giá trị:
      #  + pin (nhập mã PIN)
      #  + chatInput (nhập mật khẩu vào thanh chat, vd: /login <pass>)
      #  + auth (là server cần tải khoản có bản quyền)
      type: pin
      # Các thông số dưới có 2 dạng:
      # + Một chuỗi (vd: 'nhập /login để vào server') hoặc một con số (vd: 63)
      # + Một mảng chứa chuỗi (vd: ['nhập /login để vào server']) hoặc chứa số (vd: [63, 64])
      chatSign: # Các tin nhắn để cho bot biết để nhập Pass
      windowSlot: 63 # Số lượng ô trong cửa sổ hiện lên để cho bot nhập pin

# Các cài đặt liên quan đến thanh trạng thái của Discord Bot
status:
  # Kiểu trạng thái, có 2 dạng:
  #  + discord (các thay đổi trạng thái theo văn bản cho trước)
  #  + minecraft (thay đổi theo tình trạng kết nối đến server)
  type: discord
  # Khi để type là discord
  discord:
    text: [
        "OggyTheCode made by VaitoSoi#2200", # Nên giữ :)
        # ...
      ] # Các dòng văn bản để hiễn thị trên thanh trạng thái
    status: online # Trạng thái để hiển thị, cỏ thể là: online, dnd, idle, invisible
    updateInterval: 5m # Thời gian đến cập nhật thanh trạng thái (viết theo định dạng h, m, s; vd: 5m)
  # Khi để type là minecraft
  minecraft:
    # Các trạng thái có thể là: online, dnd, idle, invisible
    connect: online # Trạng thái khi bot đã kết nối đến server
    disconnect: idle # Trạng thái khi bot đang mất kết nối với server

# Cài đặt liên quan đến Database
# Lưu ý: Hiện tại chỉ hỗ trợ MongoDB
database:
  link: # URL để kết nối với database

# Không cần quan tâm đâu :v
express:
  port: 8000

# Dành riêng cho các lập trình viên.
# Nó đụng chạm trực tiếp đến cách bot hoạt động nên hãy cẩn thận.
developer:
  timezone: # Múi giờ của bot, mặc định theo hệ thống (xem thêm tại đây: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
  handlerPath: # Đường dẫn vào các file command và event
    commands: # Đường dẫn vào các file command
      discord: # Của Discord
      mineflayer: # của mineflayer
    events: # Đường dẫn vào các file event
      discord: # Của Discord
      mineflayer: # của mineflayer
  customScript: # Đường dẫn vào file custom script của bot
